nameSuffix: -dev
namespace: dev


images:
- name: images
  newName: nginx
  newTag: 1.23.3-alpine

replicas:
- name: deploy
  count: 1

patchesJson6902:
- target:
    version: v1
    name: deploy
    kind: Deployment
  path: deploy.patch.yml


  # - service.patch.yml
  # - ingress.patch.yml

resources:
  - ../../base