nameSuffix: -dev
namespace: dev

replicas:
  - name: deploy
    count: 1

patchesJson6902:
- target:
    kind: Deployment
    name: deploy
  patch: |-
    - op: replace
      path: /metadata/labels/
      value:
        app: deploy-dev
    - op: replace
      path: /spec/selector/matchLabels/0/app
      value: deploy-dev
    - op: replace
      path: /spec/template/metadata/labels/0/app
      value: deploy-dev
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: deploy-dev
    - op: add
      path: /spec/template/spec/containers/0/command
      value: ['sh', '-c', 'echo', '"dev"', '>', '/usr/share/nginx/html/index.html']

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: service
  patch: |-
    - op: replace
      path: /spec/selector/app
      value: service-dev

patchesJson6902:
- target:
    version: v1
    kind: Ingress
    name: ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/http/paths/0/backend/service/name
      value: service-dev
    - op: replace
      path: /spec/rules/0/host
      value: dev.local

images:
- name: images
  newName: nginx
  newTag: 1.23.3-alpine

resources:
  - ../../base